### ISSUE TITLE
[Feature request] adding fallback_branch entry to staged.dependencies.yaml

### ISSUE THREAD

**Issue by shajoezhu** [openpharma/staged.dependencies#149]
Dear maintainers

Would it be ok to add fallback_branch as one of the field, in case that main is not master branch? for example

```yaml
upstream_repos:
  insightsengineering/rbmi:
    repo: insightsengineering/rbmi
    host: https://github.com
    fallback_branch: master
```

Then update the Executing script when pressing "Install Upstream Dependencies"

Many thanks!
Joe
